### PR TITLE
added requirements.txt file 

### PR DESCRIPTION
**Pull request by Prakyathkantharaju**
- Added requirements.txt
- updated Readme.md

### CODE REVIEW

**Comment by karpathy** [comment]
Awesome ty! But I don't believe all of these are needed?

**Comment by karpathy** [comment]
eg the following are suspect: click, its dangerous, Jinja (comes with flask?), job lib, markup, scipy, sgmllib3k, threadpoolctl, Werkzeug? at least?

click==8.0.3
 feedparser==6.0.8
 Flask==2.0.2
 itsdangerous==2.0.1
 Jinja2==3.0.3
 joblib==1.1.0
 MarkupSafe==2.0.1
 numpy==1.21.4
 scikit-learn==1.0.1
 scipy==1.7.3
 sgmllib3k==1.0.0
 sklearn==0.0
 sqlitedict==1.7.0
 threadpoolctl==3.0.0
 Werkzeug==2.0.2

**Comment by e-tornike** [comment]
Minimal dependencies (w/o version testing) are:

```
feedparser==6.0.8
Flask==2.0.2
numpy==1.21.4
scikit-learn==1.0.1
sqlitedict==1.7.0
```

Optional:

```
sendgrid==6.9.2
```

**Comment by Prakyathkantharaju** [comment]
I did pip freeze to get the dependencies after minimal dependency installation. 
As @e-tornike mentioned. PIP will install the remaining dependencies in the txt file anyway.

**Comment by karpathy** [comment]
I'm not super fan of strict equality requirements coming from pip freeze. Any thoughts on simply the following candidate requirements.txt: ?

```
feedparser
numpy
scikit-learn
Flask
sqlitedict
```

**Comment by karpathy** [comment]
Adjusted the requirements, readme etc and pushed with https://github.com/karpathy/arxiv-sanity-lite/commit/6df5f1d178d01b5d8374b44b1c3460ae31d7d98d . Ty for help here, closing this.

**Pull request closed without merging**
